### ISSUE TITLE
BUG: gas switch event not serialized to XML on manually added dives

### ISSUE THREAD

**Issue by TheClockTwister** [Subsurface-divelog/subsurface#3966]
Guys, thanks for this awesome tool!

### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

When adding a dive manually that uses more than 1 cylinder, the gas change event is not saved to the XML. It is shown in the editor for the time of editing, but when de-selecting and re-selecting the dive, they dissappear from the profile. Having a look at the XML reveals, that they are not saved to file.

### Issue long description:

- When adding log entries via "Add dive", the gas change events are not applied in the profile viewer and not saved to XML
- When adding the same dive via "Plan dive" and planning it for the past, the gas change events are shown in the profile viewer and saved to XML
- A dive that was created manually via "Add dive" (not planned) can be edited via "Edit dive in planner" and if the gas change event is added there, it is saved to the XML

--> Therefore, the bug only persists when adding multi-gas dives via "Add dive"

### Operating system:

- Windows 10 Pro (10.0.19045 Build 19045)
- AMD Ryzen 7 7700X

### Subsurface version:

- Official Release v5.0.10
- Downloaded from homepage @ 27.09.23

### Steps to reproduce:

1. Create an empty log book
2. Add a dive **via the "Log > Add dive" option**
3. Configure the following cylinders:
   - 12L 200bar: 200bar-50bar, AIR
   - 6L 200bar: 200bar-60bar, EAN40
4. Create an arbitrary dive profle/curve in the editor
5. Try to add a gas switch for any given point
   - When I right-click a point in the profile, it does not even show me the EAN40, just AIR, (but that's a different bug...)
7. Save via CTRL+S
8. have a look at the generated XML file and see, that the gas switch has not been saved
9. de-select the dive by clicking somewhere else in the dive log list
10. now select the dive again and see that the gas switch is missing and the shown calculations are therefore incorrect

### Mentions:

I'm an expert on C++, but I'm quite OK with it. If you can give me a hint on where to find the methods related to event saving etc, I can see if I can fix it myself and open a PR... ;)

**Comment by mikeller** [comment]
Ok, I think the problem here is that a gas change is not represented in Subsurface in the way you think it is: A gas change is an event in the dive log - having a gas listed in the Equipment tab only does not make Subsurface consider it 'used' during a dive.

There is a preference setting to allow the user to choose if they want unused gases shown in the gas list or not, and this is off in your configuration:

![image](https://github.com/subsurface/subsurface/assets/4742747/d66e3f3f-0055-4877-a396-c9442482ddd0)


But the second bug that you are reporting about not being able to enter a gas switch for a newly created manually added dive is definitely a problem. And together with the configuration setting above this means that additional gases are not shown for you because you can't add the gas changes required to make them used:

![image](https://github.com/subsurface/subsurface/assets/4742747/d905343e-bf1b-445e-9a26-611596ef4aa5)

Let me know if you are keen to fix this bug, and I can give you pointers for where the context menu is generated.
