### ISSUE TITLE
Imperial Tank Sizes broken after Crash

### ISSUE THREAD

**Issue by Patrick-BS** [Subsurface-divelog/subsurface#4239]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

After a crash in the Planner, the tanksizes are broken. When adding a tank in planner or to a dive there is the complete volume (Size x Pressure) shown in liters. 

### Operating system:

Win10

### Subsurface version:

6.0.5144

### Steps to reproduce:

No Idea...

### Current behavior:

Choose AL80 and it will add the follwing data to the table: AL80 | 2.265,3l | 207bar. This happens to all imerial sizes.

### Expected behavior:

Choose AL80 and it will add the follwing data to the table: AL80 | 11,1l | 207bar.

### Additional information:

I think the prefrences / config file is broken. But uninstalling, deleting the appdata folders and reinstall did not help.

![AL80](https://github.com/subsurface/subsurface/assets/171980975/f0527f79-70e6-4815-bedc-52c0aa54e3c3)

**Comment by mikeller** [comment]
Looks like your preferences are set to a mix of metric and imperial - have you tried opening Preferences / Units and selecting 'metric'?

![image](https://github.com/subsurface/subsurface/assets/4742747/a30cd679-b957-487d-b1df-0ead6edead08)

**Comment by Julaye** [comment]
I had the same issue with ALxx tanks after a crash in the planner. I need to change manually the size of the tank.

I'm only in metrics

![image](https://github.com/subsurface/subsurface/assets/35028797/dba00ba7-f7af-47a5-bdfa-630d6eec86b3)

![Capture d’écran 2024-06-07 à 08 23 28 (2)](https://github.com/subsurface/subsurface/assets/35028797/f68180a5-f9c9-43fb-85c9-5349c6692e73)

**Comment by mikeller** [comment]
@Julaye: Can you reproduce the crash? It's hard to figure out what is causing the corruption without being able to reproduce.

**Comment by Julaye** [comment]
Since the crash who seems to have caused the corruption on some tank volumes, the planification mode is very stable and I can't reproduce the crash :( sorry. 

I try again this morning playing with the planification mode but without success to crash it.

Anyway, how can I restore the tanks volume to initial data ? perhaps will help me to reproduce the crash.

**Comment by mikeller** [comment]
Wait, you got the '1415.8l' tank volume despite having 'metric' selected in the preferences - that is very odd indeed. But the good news is that I found a reproduction - I'll be having a look to see what's going on.

**Comment by Patrick-BS** [comment]
Yeah thats the whole point of it. I am using it all in metric. But since the AL80 is now set to 2.265,3l instead of 11.1 it calculates 2.265,3l x 207 bar = *way too much gas* :)

**Comment by Patrick-BS** [comment]
Where are the tank parameters stored? Maybe it would be a quick fix to delete the properties and reinstall subsurface.

**Comment by mikeller** [comment]
> Where are the tank parameters stored? Maybe it would be a quick fix to delete the properties and reinstall subsurface.

They are stored in the dive log. But for what I can see (without deeper investigation) the ridiculous sizes are calculated on the fly due to a bug, but not actually stored (until you use one of these tanks in one of your dive plans and store it).

**Comment by mikeller** [comment]
I've had a look, and the culprit here is that in the current implementation, Subsurface makes incorrect assumptions about tank sizes if there is no size set for a tank that appears in a dive log.
So you must have one or more dives in your log that has 'AL80' (@Patrick-BS) or 'AL50' (@Julaye) as the type, but no size set, like this:
![image](https://github.com/subsurface/subsurface/assets/4742747/c73d5b92-3a65-4c28-829d-3fdc69460aad)

This confuses Subsurface, and gets it to calculate a 'size' in an incorrect way.
I am keen to look into a fix for this, but at the moment we are about to add a fundamental change for how this is done (#4198), and it is better to wait until this is done.
For now, the workaround is to go through your dive log, find these tanks, and enter the correct size for them, which will restore the expected behaviour.

**Comment by Patrick-BS** [comment]
Hmm, i am quiete sure that i have this problem with any "imperial style cylinder" i never used , but i will check.

**Comment by mikeller** [comment]
> Hmm, i am quiete sure that i have this problem with any "imperial style cylinder" i never used , but i will check.

If this is the case, would you be willing to share your dive log with me? You can send it to github@ike.ch.
