### ISSUE TITLE
Cannot download dives from Scubapro G3

### ISSUE THREAD

**Issue by p-neves** [Subsurface-divelog/subsurface#4320]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I cannot download dives from my scubapro G3 divecomputer using bluetooth. Subsurface connects to the G3 and the data seems to be read, as I see changes on the progress bar. At the final stage I get a "Dive data import error".

### Operating system:
Arch Linux; EN-US 
Dell XPS laptop 

### Subsurface version:
Latest master; compiled from source

Yes

1a3bc9bf7129af837b712fc9bb34bfa06a55dfa1

### Steps to reproduce:

1) Import from Dive computer (Ctrl-D);
2) Select vendor (Scubapro) and Dive computer (G3) (already paired with my system)
3) Select "Choose bluetooth download mode"
4) Click "Download" button

### Current behavior:
The download process starts after a connection is established with the G3. The progress bar advances but stops with an error ("Dive data import error".)

### Expected behavior:
The download should complete and the dives should be added to my log.

### Additional information:

[subsurface_G3_12-09-2024.log](https://github.com/user-attachments/files/16974617/subsurface_G3_12-09-2024.log)

**Comment by jefdriesen** [comment]
The build you're using is missing libdivecomputer commit [eb4b082b1b4376cfb53d3925c8a49b2777c771fc](https://github.com/libdivecomputer/libdivecomputer/commit/eb4b082b1b4376cfb53d3925c8a49b2777c771fc). You probably forgot to update the libdivecomputer submodule.

The subsurface BLE backend should have returned an error here, to indicate libdivecomputer requested a packet that is smaller than the received packet, but it returned a truncated packet and delivered the remainder of the packet on the next request instead. Unfortunately that approach doesn't work here and actually results in data loss. That's because with the Scubapro BLE protocol the first byte of each BLE packets contains non-payload data that needs to be removed by libdivecomputer. So truncating the BLE packet results in a payload byte getting lost. This problem was introduced with commit 890d4c3d649dd55817d4bb85d62ad433a61cebe4.

**Comment by p-neves** [comment]
That does it. Thanks Jef
