### ISSUE TITLE
DIve Planner: Stop times per additional metre and minute always zero

### ISSUE THREAD

**Issue by BlackFire01** [Subsurface-divelog/subsurface#4368]
![stoptimes](https://github.com/user-attachments/assets/301bf978-0f93-4195-9b6a-3d9751091c1c)

### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I have been using Subsurface to plan a lot of dives. A useful feature has always been the deco penalty per additional metre of depth and minute stayed at maximum depth. However, upon upgrading from an earlier version to the latest relase and/or nightly build, I discovered that these values are now always zero, no matter the dive plan.

### Operating system:

Windows 11, English.

### Subsurface version:

Subsurface 6.0.5286-CICD-release

### Steps to reproduce:

1) Go to Dive Planner
2) Create any deco dive plan
3) Check out the top of the dive plan window; additional deco per meter depth and minute will read 0:00

### Current behavior:

These values do not show.

### Expected behavior:

The values are calculated and displayed, as was the case a few version prior.

### Additional information:

See attached example dive plan.

**Comment by mikeller** [comment]
Additional context:
- needs 'calculate plan variations' to be enabled
- doesn't happen in 6.0.5224 (6d43b8e3343865732cdd0ed6d8b65828c28db622)

**Comment by mikeller** [comment]
@bstoeger: A quick bisect shows #4313 as the source for this.

**Comment by atdotde** [comment]
I tried to the bottom of this but without much success. It seems the problem is not in the "running this in the background" or juggling with modified copies of the dive plan (and the related question of who or what owns certain pointers). But rather that the vector of deco stops that the plan() function is supposed to return seems to be always empty. Or the debugger tricked me somehow.

I am so glad we replaced the ugly but working code by something that makes sure no pointers are dangling around anymore but which I lack the ability to reason about.

**Comment by bstoeger** [comment]
I'll look into it. But first I have to recompile from scratch because I upgraded my OS.

> I am so glad we replaced the ugly but working code by something that makes sure no pointers are dangling around anymore but which I lack the ability to reason about.

Instead of that "clever" passive-aggressive remark you could have simply asked me to clarify what is unclear to you and we could have discussed on how to properly solve this. The comment is also ironic, as I assure you that I have spent at least an order of magnitude more time trying and failing to understand the planner code.

Sometimes, I find the toxic attitudes in the open-source community so tiresome... :-(

**Comment by bstoeger** [comment]
> A quick bisect shows #4313 as the source for this.

Thanks for bisecting. I believe the problem is that the `DivePlannerPointsModel::cloneDiveplan()` function did not what the name implies (cloning the dive plan), but only copies up to a certain point:
```
        while (src && (!src->time || src->entered)) {
                *dp = (struct divedatapoint *)malloc(sizeof(struct divedatapoint));
                **dp = *src;
                dp = &(*dp)->next;
                src = src->next;
        }       
        (*dp) = NULL;
```
This was (naively) replaced by a simple assignment, which then copies the whole thing, which in turn makes the `plan()` function fail.

I will sleep on this, but I reckon the best way to fix this is to reinstate the `cloneDivePlan()` function and add a fat comment concerning this weird behavior.
